repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
    args: [--allow-multiple-documents]
    exclude: ^(k8s/deploy/charts|apps/beacon/chart)/templates/
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: check-json
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.20
  hooks:
  - id: terraform-fmt
