#!/bin/bash
# git-cleanup-repo
#
# Author: Rob Miller <rob@bigfish.co.uk>
# Adapted from the original by Yorick Sijsling

git cd

# Make sure we're working with the most up-to-date version of master.
git pull upstream HEAD --tags

git fetch

_default=$(git sd)

# Prune obsolete remote tracking branches. These are branches that we
# once tracked, but have since been deleted on the remote.
git remote prune origin

# List all the branches that have been merged fully into master, and
# then delete them. We use the remote master here, just in case our
# local master is out of date.
git branch --merged origin/$_default | grep -v "$_default$" | xargs --no-run-if-empty git branch -d

# Now the same, but including remote branches.
MERGED_ON_REMOTE=`git branch -r --merged origin/$_default | sed 's/ *origin\///' | grep -v "$_default$"`

if [ "$MERGED_ON_REMOTE" ]; then
    echo "The following remote branches are fully merged and will be removed:"
    echo $MERGED_ON_REMOTE

    read -p "Continue (y/N)? "
    if [ "$REPLY" == "y" ]; then
        git branch -r --merged origin/$_default | sed 's/ *origin\///' \
            | grep -v "$_default$" | xargs --no-run-if-empty -I% git push origin :% 2>&1 \
            | grep --colour=never 'deleted'
        echo "Done!"
    fi
fi
