#!/usr/bin/env bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
set -e
set -o pipefail

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2


for DIR in `exec git diff --cached --name-status $against | awk '$1 != "R" { print $2 }' | xargs -rn1 dirname | xargs -rn1 realpath`; do
	if [ -f "$DIR/.terraform-docs.yml" ]; then
	    cd "$DIR"
	    docker run --rm --volume "$(pwd):/terraform-docs" -u $(id -u) quay.io/terraform-docs/terraform-docs:0.18.0 markdown /terraform-docs
	fi
done

if git status --porcelain | grep -E '^[ ]' | grep -q README.md; then
    echo "ERROR: some README.md files have changed"
    exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
